#!/usr/bin/env bash
# ===========================================================================
# Copyright 2026 Afchine Madjlessi <afchine.mad@gmail.com>
# SPDX-License-Identifier: Apache-2.0
# ===========================================================================
# ci_install_openssl_fips.sh --- Debian's OpenSSL FIPS provider, installed and
# activated the way the maintainer's workstation has it, for CI jobs that must
# initialise a SIGNED module.
#
# Why this exists. A signed module loads the FIPS provider in C_Initialize and
# refuses to start without it (CKR_PROVIDER_UNAVAILABLE). No CI image has one:
# Dockerfile.build installs libssl-dev and not openssl-provider-fips, although
# its header says the provider comes from apt; and every job that initialises
# the module sets FHSM_INTEGRITY_ALLOW_UNSIGNED, which skips the provider. So
# the path a deployment runs had never run in CI. Found on 2026-09-30, when the
# first job to try it -- pkcs11-check-signed -- failed at C_InitToken.
#
# The first version of this script built OpenSSL 3.5.7 from source into
# /usr/local/ssl, on the stated ground that the workstation did the same. It
# does not: there is no /usr/local/ssl on it. It runs Debian's libssl with
# Debian's packaged provider. The premise came from the Makefile's default
# OPENSSL_PREFIX and was never checked. The run under it -- a module compiled
# against Debian's headers and run on a separately built libcrypto -- failed
# ten tests in each profile that the workstation passes. That setup is gone;
# whether it was the whole cause is for the next run to say.
#
# What the workstation has, and what this reproduces:
#   - openssl-provider-fips from apt, matching the installed libssl
#   - /usr/lib/ssl/fipsmodule.cnf generated by `openssl fipsinstall`, run with
#     OPENSSL_CONF=/dev/null (docs/AGD_PRE.md 3.3.1: through the ambient
#     configuration it loads a provider it is about to replace, and fails)
#   - the system openssl.cnf including that file and naming fips_sect
# OPENSSL_CONF is not set for the harness: the system file is the default.
# ===========================================================================
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq --no-install-recommends openssl openssl-provider-fips

MODULES="$(openssl version -m | sed 's/^MODULESDIR: //; s/"//g')"
FIPSCNF=/usr/lib/ssl/fipsmodule.cnf
SYSCNF="$(readlink -f /usr/lib/ssl/openssl.cnf)"

[ -f "$MODULES/fips.so" ] \
    || { echo "::error::openssl-provider-fips installed no $MODULES/fips.so"; exit 1; }

OPENSSL_CONF=/dev/null openssl fipsinstall -out "$FIPSCNF" -module "$MODULES/fips.so"

# Activate it in the system configuration. The shipped file carries both
# lines commented out; the edit is checked rather than trusted, so a file that
# changes shape fails here and not at C_InitToken.
sed -i -e "s|^# *\.include fipsmodule\.cnf|.include $FIPSCNF|" \
       -e 's|^# *fips = fips_sect|fips = fips_sect|' "$SYSCNF"
grep -q "^\.include $FIPSCNF" "$SYSCNF" \
    || { echo "::error::$SYSCNF: the fipsmodule.cnf include was not enabled"; exit 1; }
grep -q '^fips = fips_sect' "$SYSCNF" \
    || { echo "::error::$SYSCNF: the fips provider was not enabled"; exit 1; }

# Print what was configured, so a run can be compared with the workstation
# line by line, then prove the provider loads and passes its self-test.
openssl version
grep -nE '^\s*(\.include|openssl_conf|providers|fips|default|activate)' "$SYSCNF"
grep -vE '^\s*(#|$)|module-mac' "$FIPSCNF"
openssl list -providers | tee /dev/stderr | grep -A3 -i 'fips' | grep -qi 'status: active' \
    || { echo "::error::the FIPS provider does not load from $SYSCNF"; exit 1; }
echo "== FIPS provider active from $SYSCNF"
